import Head from 'next/head';
/* Common Commponents */
import Header from '../components/header';
/* CSS */
import styles from '../styles/Home.module.css';

const About = () => {
    console.log("About");
    return (
        <div className="container">
            <Head>
                <title>Next Example - 關於我們</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Header />
            <div>About Page</div>
        </div>
    )
}

export default About;